// Auth + Tenant + Onboarding error codes for the walking skeleton.
// Sourced from reference/error-codes.md and docs/14-onboarding-and-auth.md Part 6.
// A generator script will produce this file from the markdown source in a later sprint.

export const ErrorCodes = {
  // AUTH
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_TENANT_MISMATCH: 'AUTH_TENANT_MISMATCH',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_DOCTOR_TOKEN_EXPIRED: 'AUTH_DOCTOR_TOKEN_EXPIRED',
  AUTH_DOCTOR_TOKEN_INVALID: 'AUTH_DOCTOR_TOKEN_INVALID',
  AUTH_INVITE_TOKEN_EXPIRED: 'AUTH_INVITE_TOKEN_EXPIRED',
  AUTH_INVITE_TOKEN_USED: 'AUTH_INVITE_TOKEN_USED',
  AUTH_INVITE_TOKEN_REVOKED: 'AUTH_INVITE_TOKEN_REVOKED',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_PASSWORD_REUSED: 'AUTH_PASSWORD_REUSED',
  AUTH_PASSWORD_RESET_LIMIT_REACHED: 'AUTH_PASSWORD_RESET_LIMIT_REACHED',
  AUTH_IP_NOT_ALLOWED: 'AUTH_IP_NOT_ALLOWED',
  AUTH_DEVICE_NOT_TRUSTED: 'AUTH_DEVICE_NOT_TRUSTED',
  AUTH_CONCURRENT_SESSION_LIMIT: 'AUTH_CONCURRENT_SESSION_LIMIT',
  AUTH_SUSPICIOUS_LOGIN: 'AUTH_SUSPICIOUS_LOGIN',
  AUTH_HPR_VERIFICATION_FAILED: 'AUTH_HPR_VERIFICATION_FAILED',
  AUTH_MFA_ALREADY_ENROLLED: 'AUTH_MFA_ALREADY_ENROLLED',
  AUTH_MFA_NOT_ENROLLED: 'AUTH_MFA_NOT_ENROLLED',
  AUTH_BACKUP_CODE_INVALID: 'AUTH_BACKUP_CODE_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSE_DETECTED: 'AUTH_REFRESH_TOKEN_REUSE_DETECTED',
  AUTH_PASSWORD_CHANGE_REQUIRED: 'AUTH_PASSWORD_CHANGE_REQUIRED',

  // TENANT
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_DISABLED: 'TENANT_DISABLED',
  TENANT_NHCX_NOT_CONFIGURED: 'TENANT_NHCX_NOT_CONFIGURED',
  TENANT_PMJAY_NOT_CONFIGURED: 'TENANT_PMJAY_NOT_CONFIGURED',
  TENANT_LIFECYCLE_TRANSITION_INVALID: 'TENANT_LIFECYCLE_TRANSITION_INVALID',
  TENANT_NHCX_CERT_INVALID: 'TENANT_NHCX_CERT_INVALID',
  TENANT_NHCX_CERT_EXPIRED: 'TENANT_NHCX_CERT_EXPIRED',
  TENANT_NHCX_CERT_NOT_UPLOADED: 'TENANT_NHCX_CERT_NOT_UPLOADED',
  TENANT_PMJAY_STATE_NOT_SUPPORTED: 'TENANT_PMJAY_STATE_NOT_SUPPORTED',
  TENANT_READINESS_CHECK_FAILED: 'TENANT_READINESS_CHECK_FAILED',

  // ONBOARDING
  ONBOARDING_STEP_INCOMPLETE: 'ONBOARDING_STEP_INCOMPLETE',
  ONBOARDING_OUT_OF_ORDER: 'ONBOARDING_OUT_OF_ORDER',

  // USER ADMIN (Slice B)
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVITE_RATE_LIMIT_REACHED: 'INVITE_RATE_LIMIT_REACHED',
  INVITE_NOT_PENDING: 'INVITE_NOT_PENDING',

  // PASSWORD RESET (Slice C)
  AUTH_PASSWORD_RESET_TOKEN_INVALID: 'AUTH_PASSWORD_RESET_TOKEN_INVALID',
  AUTH_PASSWORD_RESET_TOKEN_EXPIRED: 'AUTH_PASSWORD_RESET_TOKEN_EXPIRED',
  AUTH_PASSWORD_RESET_TOKEN_USED: 'AUTH_PASSWORD_RESET_TOKEN_USED',
  AUTH_PASSWORD_BREACHED: 'AUTH_PASSWORD_BREACHED',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',

  // MFA (Slice D)
  AUTH_MFA_CHALLENGE_INVALID: 'AUTH_MFA_CHALLENGE_INVALID',
  AUTH_MFA_CHALLENGE_EXPIRED: 'AUTH_MFA_CHALLENGE_EXPIRED',
  AUTH_MFA_SETUP_NOT_PENDING: 'AUTH_MFA_SETUP_NOT_PENDING',

  // PMJAY (Slice BG)
  // Server-side gate: a PMJAY tenant tried to submit preauth or
  // claim without a recent ABDM biometric verification on the case.
  // The frontend should bounce the operator to the biometric capture
  // flow, then retry the submit.
  BIOMETRIC_VERIFICATION_REQUIRED: 'BIOMETRIC_VERIFICATION_REQUIRED',
  // Adapter call (init or verify) returned a failed status — the
  // ABDM device handshake didn't complete cleanly. Surface the
  // adapter's error message to the operator so they can pick a
  // different mode (face / iris) or retry.
  BIOMETRIC_VERIFICATION_FAILED: 'BIOMETRIC_VERIFICATION_FAILED',

  // CONSENT (Slice CG — DPDP §6 hard enforcement)
  // Server-side gate: a tenant with `requireConsent=true` tried to
  // run a flow that decrypts patient PII (eligibility / preauth /
  // claim / discharge) without an active consent grant. The
  // frontend bounces the operator to the consent-capture flow,
  // captures the grant, then retries the original request. The
  // problem-detail payload includes `patientId` + `consentType`
  // so the form can pre-populate.
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',

  // PREAUTH (T1.1 — checklist enforcement gate)
  // Server-side gate: pre-auth submit blocked because one or more
  // documents the resolved checklist marks `required: true` for this
  // (phase=preauth, rail, payer, package, admissionType) have not been
  // uploaded. The frontend lists the missing types and routes the
  // operator to the document uploader, then retries the submit.
  PREAUTH_DOCUMENTS_INCOMPLETE: 'PREAUTH_DOCUMENTS_INCOMPLETE',

  // VALIDATION & GENERIC
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_ACCOUNT_LOCKED: 423,
  AUTH_MFA_REQUIRED: 401,
  AUTH_MFA_INVALID: 401,
  AUTH_SESSION_EXPIRED: 401,
  AUTH_TENANT_MISMATCH: 403,
  AUTH_INSUFFICIENT_PERMISSIONS: 403,
  AUTH_DOCTOR_TOKEN_EXPIRED: 401,
  AUTH_DOCTOR_TOKEN_INVALID: 401,
  AUTH_INVITE_TOKEN_EXPIRED: 401,
  AUTH_INVITE_TOKEN_USED: 409,
  AUTH_INVITE_TOKEN_REVOKED: 401,
  AUTH_PASSWORD_TOO_WEAK: 422,
  AUTH_PASSWORD_REUSED: 422,
  AUTH_PASSWORD_RESET_LIMIT_REACHED: 429,
  AUTH_IP_NOT_ALLOWED: 403,
  AUTH_DEVICE_NOT_TRUSTED: 401,
  AUTH_CONCURRENT_SESSION_LIMIT: 403,
  AUTH_SUSPICIOUS_LOGIN: 401,
  AUTH_HPR_VERIFICATION_FAILED: 422,
  AUTH_MFA_ALREADY_ENROLLED: 409,
  AUTH_MFA_NOT_ENROLLED: 412,
  AUTH_BACKUP_CODE_INVALID: 401,
  AUTH_REFRESH_TOKEN_INVALID: 401,
  AUTH_REFRESH_TOKEN_REUSE_DETECTED: 401,
  AUTH_PASSWORD_CHANGE_REQUIRED: 412,

  TENANT_NOT_FOUND: 404,
  TENANT_DISABLED: 403,
  TENANT_NHCX_NOT_CONFIGURED: 412,
  TENANT_PMJAY_NOT_CONFIGURED: 412,
  TENANT_LIFECYCLE_TRANSITION_INVALID: 412,
  TENANT_NHCX_CERT_INVALID: 422,
  TENANT_NHCX_CERT_EXPIRED: 412,
  TENANT_NHCX_CERT_NOT_UPLOADED: 412,
  TENANT_PMJAY_STATE_NOT_SUPPORTED: 412,
  TENANT_READINESS_CHECK_FAILED: 412,

  BIOMETRIC_VERIFICATION_REQUIRED: 412,
  BIOMETRIC_VERIFICATION_FAILED: 422,
  // 412 mirrors BIOMETRIC_VERIFICATION_REQUIRED — same shape: a
  // pre-condition (active consent) is missing; the frontend
  // captures it, then retries.
  CONSENT_REQUIRED: 412,

  // 412 — a precondition (required documents) is missing; the
  // frontend gathers them, then retries the submit. Mirrors the
  // biometric / consent precondition shape.
  PREAUTH_DOCUMENTS_INCOMPLETE: 412,

  ONBOARDING_STEP_INCOMPLETE: 412,
  ONBOARDING_OUT_OF_ORDER: 412,

  USER_ALREADY_EXISTS: 409,
  USER_NOT_FOUND: 404,
  INVITE_RATE_LIMIT_REACHED: 429,
  INVITE_NOT_PENDING: 409,

  AUTH_PASSWORD_RESET_TOKEN_INVALID: 401,
  AUTH_PASSWORD_RESET_TOKEN_EXPIRED: 401,
  AUTH_PASSWORD_RESET_TOKEN_USED: 409,
  AUTH_PASSWORD_BREACHED: 422,
  AUTH_CURRENT_PASSWORD_INCORRECT: 401,

  AUTH_MFA_CHALLENGE_INVALID: 401,
  AUTH_MFA_CHALLENGE_EXPIRED: 401,
  AUTH_MFA_SETUP_NOT_PENDING: 409,

  VALIDATION_FAILED: 422,
  INTERNAL_ERROR: 500,
  RATE_LIMITED: 429,
};
