// Slice BS — DPDP Act 2023 §8(6) breach notification template.
//
// Pure renderer: takes a BreachIncident row + the tenant slug and
// produces a structured notification payload (subject, body, fields)
// matching the elements DPDP Rules 2025 require operators to convey
// to the Data Protection Board within 72 hours of becoming aware of
// a personal-data breach. We emit the full text + a structured form;
// the structured form lets a future automated submitter post the
// same content through the DPB's API once that exists.
//
// What §8(6) needs (DPDP Rules 2025 Schedule II):
//   1. Description of the breach (incident facts).
//   2. Approximate number of data principals affected.
//   3. Categories of personal data implicated.
//   4. Likely consequences for affected principals.
//   5. Mitigation measures taken / planned.
//   6. Contact for the grievance officer.
//
// Each kind has a different stock "likely consequences" + "mitigation
// measures" line. Operators editing the rendered text downstream is
// expected — this is a starting template, not authoritative legal copy.

import {
  type BreachKind,
  type BreachSeverity,
  type DpdpNotificationPayload,
} from '@claims/contracts';

export interface RenderInput {
  incidentId: string;
  tenantSlug: string;
  tenantDisplayName: string;
  // Optional — most tenants will have a grievance officer email
  // configured. Falls back to a placeholder if missing so the
  // template doesn't render with an empty contact line.
  grievanceOfficerContact: string | null;
  kind: BreachKind;
  severity: BreachSeverity;
  openedAt: Date;
  dueAt: Date;
  description: string;
  affectedDataPrincipals: number;
  dataCategories: string[];
}

// Keep stock copy short and operationally useful — operators will
// edit it for the actual filing. The intent is to reduce blank-page
// burden during a 72-hour deadline, not to lawyer the response.
const CONSEQUENCES: Record<BreachKind, string> = {
  BURST_DECRYPT:
    'A platform user accessed an unusually large volume of encrypted personal data over a short window. ' +
    'If the access was unauthorised or beyond the user\'s legitimate need-to-know, affected data principals ' +
    'face risk of identity-linked harm (impersonation, social-engineering, unauthorised use of identifiers) ' +
    'until access is reviewed and contained.',
  MANUAL_REPORT:
    'See incident description for the operator\'s assessment of likely consequences.',
};

const MITIGATIONS: Record<BreachKind, string> = {
  BURST_DECRYPT:
    '1. The acting user account has been flagged for review. ' +
    '2. The access ledger row(s) supporting this incident are preserved (append-only) for forensic review. ' +
    '3. Pending review outcome, the account will be suspended or its decrypt-grants narrowed. ' +
    '4. Affected data principals will be individually notified in line with §8(6) timelines once the scope is confirmed.',
  MANUAL_REPORT:
    'See incident description for the operator\'s mitigation plan.',
};

export function renderDpdpNotification(input: RenderInput): DpdpNotificationPayload {
  const subject =
    `[DPDP §8(6) — ${input.severity.toUpperCase()}] Personal data breach notification — ` +
    `${input.tenantDisplayName} (incident ${input.incidentId.slice(0, 8)})`;

  const grievance =
    input.grievanceOfficerContact ?? '[grievance officer contact pending — operator must populate before submission]';

  const consequences = CONSEQUENCES[input.kind];
  const mitigations = MITIGATIONS[input.kind];

  const body = [
    `To: Data Protection Board of India`,
    `From: ${input.tenantDisplayName} (${input.tenantSlug}) — operator under DPDP Act 2023`,
    `Subject: ${subject}`,
    ``,
    `Notification of personal data breach — DPDP Act 2023 §8(6)`,
    ``,
    `Incident reference: ${input.incidentId}`,
    `Incident kind: ${input.kind}`,
    `Severity: ${input.severity}`,
    `Detected at: ${input.openedAt.toISOString()}`,
    `72-hour notification deadline: ${input.dueAt.toISOString()}`,
    ``,
    `1. Description of the breach`,
    `   ${input.description}`,
    ``,
    `2. Approximate number of data principals affected`,
    `   ${input.affectedDataPrincipals}`,
    ``,
    `3. Categories of personal data implicated`,
    `   ${input.dataCategories.join(', ')}`,
    ``,
    `4. Likely consequences for affected principals`,
    `   ${consequences}`,
    ``,
    `5. Mitigation measures taken or planned`,
    `   ${mitigations}`,
    ``,
    `6. Grievance officer contact`,
    `   ${grievance}`,
    ``,
    `This notification was generated by the operator's claims-processing platform. ` +
    `Operators are expected to review and edit each section before formal submission.`,
  ].join('\n');

  return {
    subject,
    body,
    fields: {
      incidentId: input.incidentId,
      tenantSlug: input.tenantSlug,
      incidentKind: input.kind,
      severity: input.severity,
      openedAt: input.openedAt.toISOString(),
      dueAt: input.dueAt.toISOString(),
      description: input.description,
      affectedDataPrincipals: input.affectedDataPrincipals,
      dataCategories: input.dataCategories,
      likelyConsequences: consequences,
      mitigationMeasures: mitigations,
      grievanceOfficerContact: grievance,
    },
  };
}

// 72 hours expressed as a Date offset. Centralised so the deadline
// calculation is a single source of truth across the service +
// detector + dashboard.
export const DPDP_NOTIFICATION_WINDOW_MS = 72 * 60 * 60 * 1000;
