// Canonical audit event types — see docs/14 Part 4 for the full list.
// Events grow per-sprint as features land. Treat additions as breaking
// only if external dashboards consume the action string.

export const AuditEvents = {
  // Auth (Slice A)
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_FAILED_LOGIN: 'USER_FAILED_LOGIN',
  USER_LOCKED: 'USER_LOCKED',
  USER_UNLOCKED: 'USER_UNLOCKED',
  SESSION_REVOKED: 'SESSION_REVOKED',

  // Invitation (lands in Slice B)
  USER_INVITED: 'USER_INVITED',
  USER_ACCEPTED_INVITE: 'USER_ACCEPTED_INVITE',
  USER_INVITE_RESENT: 'USER_INVITE_RESENT',
  USER_INVITE_REVOKED: 'USER_INVITE_REVOKED',

  // Password (Slice C)
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',
  USER_PASSWORD_RESET_COMPLETED: 'USER_PASSWORD_RESET_COMPLETED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',

  // MFA (Slice D)
  USER_MFA_ENROLLED: 'USER_MFA_ENROLLED',
  USER_MFA_DISABLED: 'USER_MFA_DISABLED',
  USER_MFA_RESET_BY_ADMIN: 'USER_MFA_RESET_BY_ADMIN',

  // Lifecycle / RBAC
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_DELETED: 'USER_DELETED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',

  // Doctor (Slice F)
  DOCTOR_SIGNATURE_REQUESTED: 'DOCTOR_SIGNATURE_REQUESTED',
  DOCTOR_SIGNATURE_TOKEN_USED: 'DOCTOR_SIGNATURE_TOKEN_USED',
  DOCTOR_SIGNED: 'DOCTOR_SIGNED',

  // Tenant lifecycle (Slice G)
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_UPDATED: 'TENANT_UPDATED',
  TENANT_LIFECYCLE_TRANSITION: 'TENANT_LIFECYCLE_TRANSITION',
  TENANT_NHCX_CONFIGURED: 'TENANT_NHCX_CONFIGURED',
  TENANT_NHCX_CERT_ROTATED: 'TENANT_NHCX_CERT_ROTATED',
  TENANT_PMJAY_CONFIGURED: 'TENANT_PMJAY_CONFIGURED',
  TENANT_BRANDING_UPDATED: 'TENANT_BRANDING_UPDATED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_REACTIVATED: 'TENANT_REACTIVATED',
  TENANT_CHURNED: 'TENANT_CHURNED',
  TENANT_IP_ALLOWLIST_UPDATED: 'TENANT_IP_ALLOWLIST_UPDATED',
} as const;

export type AuditEvent = (typeof AuditEvents)[keyof typeof AuditEvents];
