import { ErrorCodes } from '@claims/error-codes';
import { z } from 'zod';

export const ProblemDetailsSchema = z.object({
  type: z.string(),
  title: z.string(),
  status: z.number().int(),
  code: z.enum([
    ErrorCodes.AUTH_INVALID_CREDENTIALS,
    ErrorCodes.AUTH_ACCOUNT_LOCKED,
    ErrorCodes.AUTH_MFA_REQUIRED,
    ErrorCodes.AUTH_MFA_INVALID,
    ErrorCodes.AUTH_SESSION_EXPIRED,
    ErrorCodes.AUTH_TENANT_MISMATCH,
    ErrorCodes.AUTH_INSUFFICIENT_PERMISSIONS,
    ErrorCodes.AUTH_DOCTOR_TOKEN_EXPIRED,
    ErrorCodes.AUTH_DOCTOR_TOKEN_INVALID,
    ErrorCodes.AUTH_INVITE_TOKEN_EXPIRED,
    ErrorCodes.AUTH_INVITE_TOKEN_USED,
    ErrorCodes.AUTH_INVITE_TOKEN_REVOKED,
    ErrorCodes.AUTH_PASSWORD_TOO_WEAK,
    ErrorCodes.AUTH_PASSWORD_REUSED,
    ErrorCodes.AUTH_PASSWORD_RESET_LIMIT_REACHED,
    ErrorCodes.AUTH_IP_NOT_ALLOWED,
    ErrorCodes.AUTH_DEVICE_NOT_TRUSTED,
    ErrorCodes.AUTH_CONCURRENT_SESSION_LIMIT,
    ErrorCodes.AUTH_SUSPICIOUS_LOGIN,
    ErrorCodes.AUTH_HPR_VERIFICATION_FAILED,
    ErrorCodes.AUTH_MFA_ALREADY_ENROLLED,
    ErrorCodes.AUTH_MFA_NOT_ENROLLED,
    ErrorCodes.AUTH_BACKUP_CODE_INVALID,
    ErrorCodes.AUTH_REFRESH_TOKEN_INVALID,
    ErrorCodes.AUTH_REFRESH_TOKEN_REUSE_DETECTED,
    ErrorCodes.AUTH_PASSWORD_CHANGE_REQUIRED,
    ErrorCodes.TENANT_NOT_FOUND,
    ErrorCodes.TENANT_DISABLED,
    ErrorCodes.TENANT_NHCX_NOT_CONFIGURED,
    ErrorCodes.TENANT_PMJAY_NOT_CONFIGURED,
    ErrorCodes.TENANT_LIFECYCLE_TRANSITION_INVALID,
    ErrorCodes.TENANT_NHCX_CERT_INVALID,
    ErrorCodes.TENANT_NHCX_CERT_EXPIRED,
    ErrorCodes.TENANT_NHCX_CERT_NOT_UPLOADED,
    ErrorCodes.TENANT_PMJAY_STATE_NOT_SUPPORTED,
    ErrorCodes.TENANT_READINESS_CHECK_FAILED,
    ErrorCodes.ONBOARDING_STEP_INCOMPLETE,
    ErrorCodes.ONBOARDING_OUT_OF_ORDER,
    ErrorCodes.USER_ALREADY_EXISTS,
    ErrorCodes.USER_NOT_FOUND,
    ErrorCodes.INVITE_RATE_LIMIT_REACHED,
    ErrorCodes.INVITE_NOT_PENDING,
    ErrorCodes.VALIDATION_FAILED,
    ErrorCodes.INTERNAL_ERROR,
    ErrorCodes.RATE_LIMITED,
  ]),
  detail: z.string().optional(),
  instance: z.string().optional(),
  correlationId: z.string().optional(),
  errors: z.record(z.array(z.string())).optional(),
});
export type ProblemDetailsPayload = z.infer<typeof ProblemDetailsSchema>;
